package com.dougkoellmer.shared.homecells;

import swarm.shared.structs.CellSize;
import com.dougkoellmer.shared.homecells.E_HomeCell;

//AUTOGENERATED FROM /scripts/client/build_cell_sizes.sh
class U_AutoGenHomeCellSize
{
	static CellSize getFocusedCellSize(E_HomeCell cell)
	{
		switch(cell)
		{
			case B33HIVE_LOGO: return new CellSize(512, 512);
			case BACKSCRATCHER_1: return new CellSize(640, 1040);
			case BACKSCRATCHER_2: return new CellSize(780, 605);
			case BANANA: return new CellSize(640, 512);
			case BLACKHOLE: return new CellSize(746, 583);
			case BOOMERANG: return new CellSize(910, 8900);
			case BOW_1: return new CellSize(512, 1296);
			case BOW_2: return new CellSize(512, 604);
			case CANVAS_BAG: return new CellSize(683, 512);
			case CANVAS_WRAP: return new CellSize(615, 1568);
			case COASTER_HOLDER: return new CellSize(780, 1088);
			case DINOSAURS: return new CellSize(768, 576);
			case DOORSTOP: return new CellSize(694, 512);
			case DRAGON: return new CellSize(640, 1040);
			case FIRE_POI: return new CellSize(700, 1066);
			case FIRE_POKER: return new CellSize(910, 1040);
			case FLASHLIGHT_LAMP: return new CellSize(640, 1568);
			case GLASSES_HOLDER: return new CellSize(512, 1438);
			case GUITAR_CASE: return new CellSize(683, 4493);
			case INFINITE_TOLERANCE: return new CellSize(768, 576);
			case JUGGLING_TORCHES: return new CellSize(700, 525);
			case KITCHEN_UTENSILS: return new CellSize(780, 585);
			case LADY: return new CellSize(512, 640);
			case MILKMAN: return new CellSize(512, 2640);
			case MOTHER_AND_CHILD: return new CellSize(512, 910);
			case OAR: return new CellSize(910, 2674);
			case PEACEFUL_MAN: return new CellSize(622, 512);
			case QUICKB2_LOGO: return new CellSize(512, 512);
			case RASP_HANDLE: return new CellSize(910, 2145);
			case RED_OAK_SPOON: return new CellSize(780, 1181);
			case ROSE: return new CellSize(709, 595);
			case SANDER_HOLDER: return new CellSize(512, 1040);
			case SANTOKU_SHEATH: return new CellSize(910, 1040);
			case SAVE_ANIMALS: return new CellSize(768, 576);
			case SAW_SHEATH: return new CellSize(780, 1186);
			case SHAKERS: return new CellSize(780, 585);
			case SOLAR_SYSTEM: return new CellSize(640, 512);
			case STONE_CUP: return new CellSize(910, 512);
			case SWORD: return new CellSize(910, 1040);
			case TERMINATOR_GLASSES: return new CellSize(780, 1186);
			case THROWING_KNIVES: return new CellSize(910, 512);
			case WOOD_CHAIN: return new CellSize(700, 4853);
		}

		return null;
	}
}
