package com.dougkoellmer.shared.homecells;

import swarm.shared.structs.CellSize;

//AUTOGENERATED FROM /scripts/client/build_cell_sizes.sh
class U_HomeCell
{
	static CellSize getAutoGeneratedCellSize(E_HomeCell cell)
	{
		switch(cell)
		{
			case PEACEFUL_MAN: return new CellSize(622, 512);
			case ROSE: return new CellSize(709, 595);
		}

		return null;
	}
}
