#!/bin/bash

SEARCH_DIR="../../project/war/img/cell_content"
OUT_FILE="../../project/src/com/dougkoellmer/server/homecells/U_AutoGenHomeCellSize.java"
THIS_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
THIS_PATH_SPLIT=(${THIS_PATH//dougkoellmer_com/ })
THIS_PATH=${THIS_PATH_SPLIT[1]}
THIS_FILE=`basename $0`
THIS_FILE="${THIS_PATH}/${THIS_FILE}"

printf "" > $OUT_FILE
printf "package com.dougkoellmer.shared.homecells;\n\n" >> $OUT_FILE
printf "import swarm.shared.structs.CellSize;\n\n" >> $OUT_FILE
printf "//AUTOGENERATED FROM ${THIS_FILE}\n" >> $OUT_FILE
printf "class U_HomeCell\n" >> $OUT_FILE
printf "{\n" >> $OUT_FILE
printf "\tstatic CellSize getFocusedCellSize(E_HomeCell cell)\n" >> $OUT_FILE
printf "\t{\n" >> $OUT_FILE
printf "\t\tswitch(cell)\n" >> $OUT_FILE
printf "\t\t{\n" >> $OUT_FILE
printf "" >> $OUT_FILE

for entry in "$SEARCH_DIR"/*
do
	if [[ $entry == *.solo.* ]]
	then
		split=(${entry//\// })
		length=${#split[@]}
		filename=${split[length-1]};
		split=(${filename//\./ })
		cell_name=${split[0]}
		cell_name=${cell_name^^}
		
		#width=`identify -ping '%w' $entry`
		width=$(convert $entry -format "%w" info:)
		height=$(convert $entry -format "%h" info:)
		
		printf "\t\t\tcase ${cell_name}: return new CellSize(${width}, ${height});\n" >> $OUT_FILE
		
		identify.exe -size $entry
	fi
done

printf "\t\t}\n" >> $OUT_FILE
printf "\n" >> $OUT_FILE
printf "\t\treturn null;\n" >> $OUT_FILE
printf "\t}\n" >> $OUT_FILE
printf "}\n" >> $OUT_FILE





