package com.dougkoellmer.server.homecells;

import com.dougkoellmer.shared.homecells.E_HomeCell;

import swarm.shared.structs.CellSize;

//AUTOGENERATED FROM /scripts/client/build_cell_sizes.sh
class U_AutoGenHomeCellSize
{
	static CellSize getFocusedCellSize(E_HomeCell cell)
	{
		switch(cell)
		{
			case PEACEFUL_MAN: return new CellSize(622, 512);
			case ROSE: return new CellSize(709, 595);
		}

		return null;
	}
}
