var PIPE_DIAM = .84;
var FORK_ANGLE = 18;
var PIPE_OVERHANG = .5;//.25;
var WHEEL_DIAM = 28.5;
var TIRE_THICKNESS = 2.00;
var RIM_THICKNESS = 1;
var OFFSET_FROM_AXLE = 3;
var OFFSET_FROM_TIRE_TOP = 2.5;
var BOTTOM_PIPE_LENGTH = 4;
var GRID_SIZE = 1;
var PIXELS_PER_INCH = 12;//15;
var SPOKE_WIDTH = 2;
var GRID_LINE_WIDTH = .5;
var SPOKE_COUNT = 16;
var FORK_BOTTOM_DIAM = .85; //TODO: confirm measurement
var FORK_TOP_DIAM = 1.2; // TODO: confirm measurement
var FORK_LENGTH = 18.5;
var DEFAULT_LINE_WIDTH = 1;
var CROSS_PIPE_COUNT = 4;
var TOP_PIPE_COUNT = 3;
var CENTER_V_OVERHANG = 4;
var PIPE_THROWAWAY_OVERHANG_WITH_HOLE = 1.0;
var PIPE_THROWAWAY_OVERHANG_WITHOUT_HOLE = .5;

var START_POINT = new Point(28, 31);
var SHOWING_RIGHT_SIDE = true;


var GRID_COLOR = "black";
var TIRE_COLOR = "black";
var RIM_COLOR = "grey";
var SPOKE_COLOR = "black";
var FRAME_COLOR = "#C4E4BE";
var PIPE_COLOR = "grey";



function FORK_ANGLE_RAD() {
	return (Math.PI/180.0) * FORK_ANGLE;
}
var RACK_HEIGHT = WHEEL_DIAM/2.0 + OFFSET_FROM_AXLE + OFFSET_FROM_TIRE_TOP;

function PIPE_RADIUS() {
	return PIPE_DIAM/2.0
}