var WEIGHT_MASS = 3.5;
var WEIGHT_WIDTH = 70;
var WEIGHT_HEIGHT = 66.5;
var WEIGHT_FRICTION = 3;

var TUBE_WIDTH = 250;
var TUBE_WALL_WIDTH = 10;
var TUBE_HEIGHT = 268;
var BASE_WIDTH = 268;
var BASE_HEIGHT = 60;
var BASE_Y_OFFSET = 60;
var TOP_WIDTH = 165;
var TOP_HEIGHT = 110;
var WEIGHT_BOTTOM_MINOR_RADIUS = 0;
var PIXELS_PER_METER = 30;
var INV_PIXELS_PER_METER = (1.0/PIXELS_PER_METER);
var GRAVITY_Y = 30;
var TUBE_BOTTOM_MINOR_RADIUS = 38;
var ATOM_VIBRATION_RANGE = 20;
var ATOM_RADIUS = 8;
var ATOM_MIN_VIBRATION_SPEED = 50;
var ATOM_MAX_VIBRATION_SPEED = 650;
var ATOM_FLOAT_SPEED = 5;
var ATOM_ROW_COUNT = 6;
var ATOM_COL_COUNT = 5;
var ATOM_STAGGER = 20;
var STOPPER_HEIGHT = 54;

var DEBUG_ATOM_ORIENTATION = false;

var PARTICLE_Y_OFFSET = 5;

var FLOOR_HEIGHT = TUBE_BOTTOM_MINOR_RADIUS + 40;

var TUBE_FRAME_WIDTH = 280;
var TUBE_FRAME_HEIGHT = 404;

var WEIGHT_FRAME_WIDTH = 80;
var WEIGHT_FRAME_HEIGHT = 88;

var TUBE_BOTTOM_OFFSET = -40;

var POSITION_ITERATIONS = 8;
var VELOCITY_ITERATIONS = 8;
var PISTON_DAMPING = 40;


var STAGE_WALL_CATEGORY = 0x2;
var WEIGHT_CATEGORY = 0x4;
var PLUNGER_CEILING_CATEGORY = 0x8;