var TABLE_HEIGHT = 290;
var TABLE_TOP_HEIGHT = 5;
var TABLE_TOP_WIDTH = 300;
var TABLE_TOP_THICKNESS = 15;

var TABLE_FRAME_WIDTH = 521;
var TABLE_FRAME_HEIGHT = 768;

var TABLE_BOTTOM_OFFSET = 38;

var FLOOR_HEIGHT = 75;

var BASE_HEIGHT = 15;


var BURNER_BASE_WIDTH = 134;
var BURNER_BASE_MINOR_RADIUS = 50;
var BURNER_STEM_HEIGHT = 140;
var BURNER_STEM_WIDTH = 40;
var BURNER_MASS = 3;
var BURNER_FRICTION = 5;


var BURNER_ANIMATION_WIDTH = 88;
var BURNER_ANIMATION_HEIGHT = 76;

var COOL_ANIMATION_FRAME_RATE = 1/10;
var HOT_ANIMATION_FRAME_RATE = 1/30;



var PARTICLES_PER_SECOND = 6;
var PARTICLE_LIFETIME = 2;
var PARTICLE_SPEED = 5;
var PARTICLE_PHYSICS_RADIUS = 15;
var PARTICLE_COLD_VARIANCE = 1.5;

var PARTICLE_CATEGORY = 0x10;
var BURNER_CATEGORY = 0x20;
var BURNER_BLOCKER_CATEGORY = 0x40;

var TEMPERATURE_DECAY_PER_SECOND = .4;
var TEMPERATURE_DELTA_PER_PARTICLE = .1;
var TEMPERATURE_FORCE_CONSTANT = 300;
var TEMPERATURE_VIBRATION_CONSTANT = 100;



var TUBE_BOTTOM_OFFSET = -TABLE_HEIGHT + TUBE_BOTTOM_MINOR_RADIUS + 5;
