
var FRAME_RATE = 30;

var STACK_WIDTH = 304;

var PLATFORM_CONNECTOR_HEIGHT = 7;

var STACK_PLATFORM_HEIGHT = 50;
var STACK_ROD_WIDTH = 24;
var STACK_ROD_HEIGHT = 468;
var STACK_PLATFORM_OFFSET = 75;

var LAYER_COUNT = 4;

var LAYER_WIDTH = 276;

var LAYER_1_HEIGHT = 74;
var LAYER_2_HEIGHT = 157;
var LAYER_3_HEIGHT = 120;
var LAYER_4_HEIGHT = 110;

var ERROR_SIGN_SIZE = 44;
var ERROR_SIGN_SHOW_TIME = 1; // seconds

var STACK_COUNT = 3;

var ARROW_WIDTH = 564;

var RESET_BUTTON_WIDTH = 70;

var TOUCH_ICON_SIZE = 70;